package login.and.register.app;


import java.util.Arrays;
import javax.swing.JOptionPane;


public class ShowReport extends javax.swing.JFrame {
    
    String[] name = {"Developer","Task Name","Task Duration" , "Task Status"};  
    
    String[] task1 = {"Mike Smith","Create Login","5" , "TO Do"};
    
    String[] task2 = {"Edward Harrison","Create Add Features","8","Doing"};
       
    String[] task3 = {"Samantha Paulson","Create Reports","2","Done"};
      
    String[] task4 = {"Glenda Oberholzer","Add Arrays","11","TO Do"};  
    
    
 
    
        
    
    
    

         
    public ShowReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusOfDone = new javax.swing.JButton();
        longestDuration = new javax.swing.JButton();
        searchOftaskNames = new javax.swing.JButton();
        deleteTask = new javax.swing.JButton();
        DisplayReport = new javax.swing.JButton();
        searchOfTaskStatus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        statusOfDone.setText("Status Done ");
        statusOfDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusOfDoneActionPerformed(evt);
            }
        });

        longestDuration.setText("Longest Duration");
        longestDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                longestDurationActionPerformed(evt);
            }
        });

        searchOftaskNames.setText("Search Task Name");
        searchOftaskNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOftaskNamesActionPerformed(evt);
            }
        });

        deleteTask.setText("Delete Task ");
        deleteTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTaskActionPerformed(evt);
            }
        });

        DisplayReport.setText("Display Report");
        DisplayReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayReportActionPerformed(evt);
            }
        });

        searchOfTaskStatus.setText("Search Task Status");
        searchOfTaskStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchOfTaskStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusOfDone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(longestDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchOftaskNames, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchOfTaskStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteTask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DisplayReport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusOfDone)
                    .addComponent(searchOfTaskStatus))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(longestDuration)
                    .addComponent(deleteTask))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchOftaskNames)
                    .addComponent(DisplayReport))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchOftaskNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOftaskNamesActionPerformed
        String[] task11 = task1;
        String[] task12 = task2;
        String[] task13 = task3;
        String[] task14 = task4;
        
        String name1 = task11[1].toUpperCase();
        String name2 = task12[1].toUpperCase();
        String name3 = task13[1].toUpperCase();
        String name4 = task14[1].toUpperCase();
        
        
          String m = JOptionPane.showInputDialog("Enter the Task Name");
          
          String n = m.toUpperCase();
          
        if(name1.equals(n)    ){
       
            JOptionPane.showMessageDialog(null,
                    " \n Task Name :"+ task11[1]+ ""
                    + "\n Developer :"+ task11[0] +
                    "\n Task Status :"+ task11[3]);
       } 
        
        if( name2.equals(n)   ){
       
            JOptionPane.showMessageDialog(null,
                    " \n Task Name :"+ task12[1]+ ""
                    + "\n Developer :"+ task12[0] +
                    "\n Task Status :"+ task12[3]);
       } 
        if(name3.equals(n)  ){
       
            JOptionPane.showMessageDialog(null,
                    " \n Task Name :"+ task13[1]+ ""
                    + "\n Developer :"+ task13[0] +
                    "\n Task Status :"+ task13[3]);
       } 
        if( name4.equals(n)  ){
       
            JOptionPane.showMessageDialog(null,
                    " \n Task Name :"+ task14[1]+ ""
                    + "\n Developer :"+ task14[0] +
                    "\n Task Status :"+ task14[3]);
       } 
       
        
    }//GEN-LAST:event_searchOftaskNamesActionPerformed

    private void statusOfDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusOfDoneActionPerformed
       
        String[] task11 = task1;
        String[] task12 = task2;
        String[] task13 = task3;
        String[] task14 = task4;
        
        
        
        
       if( "Done".equals(task11[3])   ){
           
           
       
            JOptionPane.showMessageDialog(null,"\n Developer :"+ task11[0] +
                    " \n Task Name :"+ task11[1]+ ""
                    + "\n Task Duration :" + task11[2]+ 
                    "\n Task Status :"+ task11[3]);
       } 
        
        if( "Done".equals(task12[3])   ){
       
            JOptionPane.showMessageDialog(null,"\n Developer :"+ task12[0] +
                    " \n Task Name :"+ task12[1]+ ""
                    + "\n Task Duration :" + task12[2]+ 
                    "\n Task Status :"+ task12[3]);
       } 
        if( "Done".equals(task13[3])   ){
       
            JOptionPane.showMessageDialog(null,"\n Developer :"+ task13[0] +
                    " \n Task Name :"+ task13[1]+ ""
                    + "\n Task Duration :" + task13[2]+ 
                    "\n Task Status :"+ task13[3]);
       } 
        if( "Done".equals(task14[3])   ){
       
            JOptionPane.showMessageDialog(null,"\n Developer :"+ task14[0] +
                    " \n Task Name :"+ task14[1]+ ""
                    + "\n Task Duration :" + task14[2]+ 
                    "\n Task Status :"+ task14[3]);
       } 
        
        
        
    }//GEN-LAST:event_statusOfDoneActionPerformed

    private void longestDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_longestDurationActionPerformed
      
        String[] task11 = task1;
        String[] task12 = task2;
        String[] task13 = task3;
        String[] task14 = task4;
        
        int taskA = Integer.parseInt(task11[2]); 
        int taskB = Integer.parseInt(task12[2]); 
        int taskC = Integer.parseInt(task13[2]); 
        int taskD = Integer.parseInt(task14[2]); 
       
             
      
      int [] arr = new int [] {taskA, taskB, taskC, taskD};  
         
        int max = arr[0];  
         
        for (int i = 0; i < arr.length; i++) {  
           
           if(arr[i] > max)  
               max = arr[i];  
        }  
        
        
             
       if( max == taskA   ){
       
            JOptionPane.showMessageDialog(null,"\n Developer :"+ task11[0] 
                    
                    + "\n Task Duration :" + task11[2] 
                    );
       } 
        
        if( max == taskB     ){
       
            JOptionPane.showMessageDialog(null,"\n Developer :"+ task12[0] 
                   
                    + "\n Task Duration :" + task12[2] 
                  );
       } 
        if( max == taskC    ){
       
            JOptionPane.showMessageDialog(null,"\n Developer :"+ task13[0] 
                   
                    + "\n Task Duration :" + task13[2]
                    );
       } 
        if( max == taskD   ){
       
            JOptionPane.showMessageDialog(null,"\n Developer :"+ task14[0]
                
                    + "\n Task Duration :" + task14[2] 
                   );
       } 
        
        
        
        
      
       

    
       
        
    }//GEN-LAST:event_longestDurationActionPerformed

    private void searchOfTaskStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchOfTaskStatusActionPerformed
       
        String[] task11 = task1;
        String[] task12 = task2;
        String[] task13 = task3;
        String[] task14 = task4;
        
        String name1 = task11[0].toUpperCase();
        String name2 = task12[0].toUpperCase();
        String name3 = task13[0].toUpperCase();
        String name4 = task14[0].toUpperCase();
        
        
          String m = JOptionPane.showInputDialog("Enter the Developer Name");
          
          String n = m.toUpperCase();
          
        if(name1.equals(n)    ){
       
            JOptionPane.showMessageDialog(null,
                    " \n Task Name :"+ task11[1]+ ""
                    + 
                    "\n Task Status :"+ task11[3]);
       } 
        
        if( name2.equals(n)   ){
       
            JOptionPane.showMessageDialog(null,
                    " \n Task Name :"+ task12[1]+ ""
                    + 
                    "\n Task Status :"+ task12[3]);
       } 
        if(name3.equals(n)  ){
       
            JOptionPane.showMessageDialog(null,
                    " \n Task Name :"+ task13[1]+ ""
                    + 
                    "\n Task Status :"+ task13[3]);
       } 
        if( name4.equals(n)  ){
       
            JOptionPane.showMessageDialog(null,
                    " \n Task Name :"+ task14[1]+ ""
                    + 
                    "\n Task Status :"+ task14[3]);
       } 
       
        
        
        
    }//GEN-LAST:event_searchOfTaskStatusActionPerformed

    @SuppressWarnings("empty-statement")
    private void deleteTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTaskActionPerformed
        
        String[] task11 = task1;
        String[] task12 = task2;
        String[] task13 = task3;
        String[] task14 = task4;
        
        
        String name1 = task11[1].toUpperCase();
        String name2 = task12[1].toUpperCase();
        String name3 = task13[1].toUpperCase();
        String name4 = task14[1].toUpperCase();
        
        String m = JOptionPane.showInputDialog("ENTER THE TASK NAME YOU WANT TO DELETE");
        
        String n = m.toUpperCase();
        
          if(name1.equals(n)    ){
       
           task11[0] = " ";
           task11[1] = " ";
           task11[2] = " ";
           task11[3] = " ";
       
         
           
        
          JOptionPane.showMessageDialog(null,
                
                     "\n Test Data Task 1 "+
                    "\n Developer :"+ task11[0] +
                    " \n Task Name :"+ task11[1]+ ""
                    + "\n Task Duration :" + task11[2]+ 
                    "\n Task Status :"+ task11[3]+
                     
                             "\n "+
                    "\n Test Data Task 2 "+
                    "\n Developer :"+ task12[0] +
                    " \n Task Name :"+ task12[1]+ ""
                    + "\n Task Duration :" + task12[2]+ 
                    "\n Task Status :"+ task12[3]+
          
                         "\n "+    
                     "\n Test Data Task 3 "+
                     "\n Developer :"+ task13[0] +
                    " \n Task Name :"+ task13[1]+ ""
                    + "\n Task Duration :" + task13[2]+ 
                    "\n Task Status :"+ task13[3]+
                      
                             "\n "+
                     "\n Test Data Task 4 "+        
                    "\n Developer :"+ task14[0] +
                    " \n Task Name :"+ task14[1]+ ""
                    + "\n Task Duration :" + task14[2]+ 
                    "\n Task Status :"+ task14[3]
        ) ;
        
         
         
         
         
       } 
        
        if( name2.equals(n)   ){
        
            
           task12[0] = " ";
           task12[1] = " ";
           task12[2] = " ";
           task12[3] = " ";
       
        
           JOptionPane.showMessageDialog(null,
                
                     "\n Test Data Task 1 "+
                    "\n Developer :"+ task11[0] +
                    " \n Task Name :"+ task11[1]+ ""
                    + "\n Task Duration :" + task11[2]+ 
                    "\n Task Status :"+ task11[3]+
                     
                             "\n "+
                    "\n Test Data Task 2 "+
                    "\n Developer :"+ task12[0] +
                    " \n Task Name :"+ task12[1]+ ""
                    + "\n Task Duration :" + task12[2]+ 
                    "\n Task Status :"+ task12[3]+
          
                         "\n "+    
                     "\n Test Data Task 3 "+
                     "\n Developer :"+ task13[0] +
                    " \n Task Name :"+ task13[1]+ ""
                    + "\n Task Duration :" + task13[2]+ 
                    "\n Task Status :"+ task13[3]+
                      
                             "\n "+
                     "\n Test Data Task 4 "+        
                    "\n Developer :"+ task14[0] +
                    " \n Task Name :"+ task14[1]+ ""
                    + "\n Task Duration :" + task14[2]+ 
                    "\n Task Status :"+ task14[3]
        ) ;
        
          
       } 
        if(name3.equals(n)  ){
       
           task13[0] = " ";
           task13[1] = " ";
           task13[2] = " ";
           task13[3] = " ";
       
              JOptionPane.showMessageDialog(null,
                
                     "\n Test Data Task 1 "+
                    "\n Developer :"+ task11[0] +
                    " \n Task Name :"+ task11[1]+ ""
                    + "\n Task Duration :" + task11[2]+ 
                    "\n Task Status :"+ task11[3]+
                     
                             "\n "+
                    "\n Test Data Task 2 "+
                    "\n Developer :"+ task12[0] +
                    " \n Task Name :"+ task12[1]+ ""
                    + "\n Task Duration :" + task12[2]+ 
                    "\n Task Status :"+ task12[3]+
          
                         "\n "+    
                     "\n Test Data Task 3 "+
                     "\n Developer :"+ task13[0] +
                    " \n Task Name :"+ task13[1]+ ""
                    + "\n Task Duration :" + task13[2]+ 
                    "\n Task Status :"+ task13[3]+
                      
                             "\n "+
                     "\n Test Data Task 4 "+        
                    "\n Developer :"+ task14[0] +
                    " \n Task Name :"+ task14[1]+ ""
                    + "\n Task Duration :" + task14[2]+ 
                    "\n Task Status :"+ task14[3]
        ) ;
        
       } 
        if( name4.equals(n)  ){
        
           task14[0] = " ";
           task14[1] = " ";
           task14[2] = " ";
           task14[3] = " ";
       
            
           JOptionPane.showMessageDialog(null,
                
                     "\n Test Data Task 1 "+
                    "\n Developer :"+ task11[0] +
                    " \n Task Name :"+ task11[1]+ ""
                    + "\n Task Duration :" + task11[2]+ 
                    "\n Task Status :"+ task11[3]+
                     
                             "\n "+
                    "\n Test Data Task 2 "+
                    "\n Developer :"+ task12[0] +
                    " \n Task Name :"+ task12[1]+ ""
                    + "\n Task Duration :" + task12[2]+ 
                    "\n Task Status :"+ task12[3]+
          
                         "\n "+    
                     "\n Test Data Task 3 "+
                     "\n Developer :"+ task13[0] +
                    " \n Task Name :"+ task13[1]+ ""
                    + "\n Task Duration :" + task13[2]+ 
                    "\n Task Status :"+ task13[3]+
                      
                             "\n "+
                     "\n Test Data Task 4 "+        
                    "\n Developer :"+ task14[0] +
                    " \n Task Name :"+ task14[1]+ ""
                    + "\n Task Duration :" + task14[2]+ 
                    "\n Task Status :"+ task14[3]
        ) ;
        
       } 
    }//GEN-LAST:event_deleteTaskActionPerformed

    private void DisplayReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayReportActionPerformed
        
        
        String[] task11 = task1;
        String[] task12 = task2;
        String[] task13 = task3;
        String[] task14 = task4;
        
        JOptionPane.showMessageDialog(null,
                
                     "\n Test Data Task 1 "+
                    "\n Developer :"+ task11[0] +
                    " \n Task Name :"+ task11[1]+ ""
                    + "\n Task Duration :" + task11[2]+ 
                    "\n Task Status :"+ task11[3]+
                     
                             "\n "+
                    "\n Test Data Task 2 "+
                    "\n Developer :"+ task12[0] +
                    " \n Task Name :"+ task12[1]+ ""
                    + "\n Task Duration :" + task12[2]+ 
                    "\n Task Status :"+ task12[3]+
          
                         "\n "+    
                     "\n Test Data Task 3 "+
                     "\n Developer :"+ task13[0] +
                    " \n Task Name :"+ task13[1]+ ""
                    + "\n Task Duration :" + task13[2]+ 
                    "\n Task Status :"+ task13[3]+
                      
                             "\n "+
                     "\n Test Data Task 4 "+        
                    "\n Developer :"+ task14[0] +
                    " \n Task Name :"+ task14[1]+ ""
                    + "\n Task Duration :" + task14[2]+ 
                    "\n Task Status :"+ task14[3]
        ) ;
        
    
    }//GEN-LAST:event_DisplayReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DisplayReport;
    private javax.swing.JButton deleteTask;
    private javax.swing.JButton longestDuration;
    private javax.swing.JButton searchOfTaskStatus;
    private javax.swing.JButton searchOftaskNames;
    private javax.swing.JButton statusOfDone;
    // End of variables declaration//GEN-END:variables
}
